### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [BenjaFriend/GameForPeopleWithPhones#1]
Hello,

I'm the creator of the Nice Vibrations asset, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.
Please remove these files from this repository within the next 24 hours, or make the repository private.
After that delay Github will take that repo down.

Thanks,
Renaud

**Comment by BenjaFriend** [comment]
Removed the nice vibrations files from the assets folder.

**Comment by reunono** [comment]
Thank you!
